export const db = {
  "items": [
      {
          "id":1,
          "name":"Pedro",
          "alive":false
      },
      {
          "id":2,
          "name":"João",
          "alive":true
      },
      {
          "id":3,
          "name":"James",
          "alive":true
      },
      {
          "id":4,
          "name":"Ferrerro",
          "alive":true
      },
      {
          "id":5,
          "name":"Melinda",
          "alive":true
      },
      {
          "id":6,
          "name":"Jackeline",
          "alive":true
      }
  ]
}